# -*- coding: utf-8 -*-
"""Renewable_Energy_Sentiment_Analysis_&_Topic_Generation (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VyWMVMGm1UZlMw9jthkyf8n3q4pIECRp
"""

!pip install gensim pyLDAvis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# For text processing
import re
from textblob import TextBlob
import gensim
import logging
import tempfile
from gensim import corpora, models, similarities
from sklearn.feature_extraction.text import CountVectorizer
import pyLDAvis.gensim_models
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Importing file and sheet

import pandas as pd

df = pd.read_excel("Twitter_Dataset_Assignment_2.xlsx", sheet_name='SDG7_Affordable_Clean_Energy')
df.head()

"""Preprocessing"""

# Transforming all text into lowercase letters
df_clean = df
df_clean['Text'] = df_clean['Text'].str.lower()

# Remove twitter IDs
def remove_twitter_ids(tweet):
  mention_removed_tweet = re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", "", str(tweet)) # remove any sequence of characters followed by '@' sign
  spaces_removed = re.sub(r"\s\s+", " ", str(mention_removed_tweet)) # remove multiple spaces
  return spaces_removed

df_clean['Text'] = df_clean['Text'].apply(remove_twitter_ids)

# Duplicate removal
df.duplicated().any()
df_clean = df.drop_duplicates()

# Puntuation removal
df_clean['Text'] = df_clean['Text'].str.replace(r'[^\w\s]','')

# Removing numbers
df_clean['Text'] = df_clean['Text'].str.replace(r'\d+', '', regex=True)



df_clean.head()

"""Stopword removal"""

# Stop word package:
# Load NLTK library
import nltk

# Download the stopwords to the nltk library
nltk.download('stopwords')

# Load the stopwords
from nltk.corpus import stopwords

stop = stopwords.words('english')
print(stop)

stop.remove('not') # may be valuable since it negates words
custom_words = {"info", "node", "imbalance"} # Remove non-essential words from Text
stop = set(stop) | custom_words # Combine stop words and custom words using set union

def remove_stop_words(tweet):
  tokens = tweet.split()
  stop_removed_tokens = [t for t in tokens if t not in stop]
  convert_to_string = " ".join(stop_removed_tokens)
  return convert_to_string

df_clean['Text'] = df_clean['Text'].apply(remove_stop_words)
df_clean.head()

"""Standarsiation using lemmitisation"""

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    tokens = text.split()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return " ".join(lemmatized_tokens)

df_clean['Text'] = df_clean['Text'].apply(lemmatize_text)
df_clean.head()

"""Word Frequency count:"""

word_frequency = pd.Series(' '.join(df_clean['Text']).split()).value_counts()

word_frequency[:10]

"""Word frequency visualisation:"""

word_count  = word_frequency
word_count = word_count[:10,]
plt.figure(figsize=(10,5))
sns.barplot(x=word_count.index, y=word_count.values, alpha=0.8)
plt.title('Tweets in top 10 words')
plt.ylabel('Number of Occurrences', fontsize=12)
plt.xlabel('Word', fontsize=12)
plt.show()

"""Word Cloud:"""

from PIL import Image
from wordcloud import WordCloud

corpus = list(df_clean['Text'])

wordcloud = WordCloud(background_color='white', max_words=200, max_font_size=50, random_state=42).generate(str(corpus))

fig = plt.figure(1)
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

"""Common word removal"""

common_words = ['power','energy','solar','outage','wind', 'flow', 'iteration', 'total']
df_clean['Text'] = df_clean['Text'].apply(lambda x: " ".join(x for x in x.split() if x not in common_words))

# Test
word_frequency = pd.Series(' '.join(df_clean['Text']).split()).value_counts()
word_count  = word_frequency
word_count = word_count[:10,]
plt.figure(figsize=(10,5))
sns.barplot(x=word_count.index, y=word_count.values, alpha=0.8)
plt.title('Tweets in top 10 words')
plt.ylabel('Number of Occurrences', fontsize=12)
plt.xlabel('Word', fontsize=12)
plt.show()

from PIL import Image
from wordcloud import WordCloud

corpus = list(df_clean['Text'])

wordcloud = WordCloud(background_color='white', max_words=200, max_font_size=50, random_state=42).generate(str(corpus))

fig = plt.figure(1)
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

"""Ngram Analysis"""

def get_ngrams(corpus, ngram_range=(2, 2)):

    # Create CountVectorizer object from sklearn library with bigrams
    vec1 = CountVectorizer(ngram_range=ngram_range, max_features=2000).fit(corpus)

    # Create BoW feature representation using word frequency
    bag_of_words = vec1.transform(corpus)

    # compute sum of words
    sum_words = bag_of_words.sum(axis=0)

    # create (word, frequency) tuples for bigrams
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec1.vocabulary_.items()]
    words_freq =sorted(words_freq, key = lambda x: x[1], reverse=True)
    return words_freq
#bigrams
bigram = get_ngrams(df_clean['Text'].tolist(), ngram_range=(2, 2))
bigram = pd.DataFrame(bigram)
bigram = bigram.rename(columns={0: 'Bigram', 1: 'Frequency'})
#trigrams
trigram = get_ngrams(df_clean['Text'].tolist(), ngram_range=(3, 3))
trigram = pd.DataFrame(trigram)
trigram = trigram.rename(columns={0: 'trigram', 1: 'Frequency'}) # Rename columns

# Bigram visualisation

top_bigrams_to_show = 20

sns.set(rc={'figure.figsize':(13,8)})
h=sns.barplot(x='Bigram', y='Frequency', data=bigram[:top_bigrams_to_show])
plt.xticks(rotation=75, ha='right')
plt.title('Bigram Analysis')
plt.show()

# Trigram visualisation

top_trigrams_to_show = 20

sns.set(rc={'figure.figsize':(13,8)})
h=sns.barplot(x='trigram', y='Frequency', data=trigram[:top_bigrams_to_show])
plt.xticks(rotation=75, ha='right')
plt.title('Trigram Analysis')
plt.show()

"""Tweet count overtime:"""

df_tweetcount = df_clean.groupby(['day'])['Text'].count().reset_index(name='tweet_count').set_index('day')
df_tweetcount.head()

df_tweetcount.plot()
plt.savefig('temporal_analysis_v2.png', dpi=800)

specific_date = df_tweetcount.loc['2025-04-22']
specific_date

# Content in specific date
for tweet in df[df['day']=='2025-04-22']['Text']:
    display(tweet)

"""Sentiment Analysis:"""

df_clean['sentiment'] = df_clean['Text'].apply(lambda x: TextBlob(x).sentiment.polarity)
df_clean[['Text', 'sentiment']].head(50)

"""Sentiment overtime:"""

df_clean.groupby(['day'])['sentiment'].mean()

df_sentiment_over_time = df_clean.groupby(['day'])['sentiment'].mean()

plt.figure(figsize=(12, 6))
df_sentiment_over_time.plot()
plt.title('Average Sentiment Over Time')
plt.xlabel('Date')
plt.ylabel('Average Sentiment')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Topic Modelling:"""

TEMP_FOLDER = tempfile.gettempdir()
print('Folder "{}" will be used to save temporary dictionary and corpus.'.format(TEMP_FOLDER))
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

# Tokenisation
texts = [[word for word in str(document).split()] for document in corpus]
texts[:5]

# Create a dictionary for all the tokenised words from previous cell
dictionary = corpora.Dictionary(texts)


dictionary.save(os.path.join(TEMP_FOLDER, 'text.dict'))
print(dictionary.token2id)

corpus = [dictionary.doc2bow(text) for text in texts]

#bag of words model
tweet_id = 0
print(texts[tweet_id]) # each tweet converted to tokens
print(dictionary.doc2bow(texts[tweet_id])) # each token is represented as a id from a dictionary

# TF-IDF model
tfidf = models.TfidfModel(corpus)
corpus_tfidf = tfidf[corpus]

total_topics = 10
lda = models.LdaModel(corpus, id2word=dictionary, num_topics=total_topics, passes = 10, iterations=200) # Passes and iteration to ensure convergence
corpus_lda = lda[corpus_tfidf]
lda.show_topics(total_topics, num_words=6)

pyLDAvis.enable_notebook()
panel = pyLDAvis.gensim_models.prepare(lda, corpus_lda, dictionary, mds='tsne')
panel

"""Generative AI to find the insights in each topic:"""

# --- Install and set up OpenAI ---
!pip install openai

import os
from openai import OpenAI

# 🔑 Add your OpenAI API key (replace with your real key)
os.environ["OPENAI_API_KEY"] = "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"
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

# --- Get topics from your LDA model ---
topics = lda.show_topics(num_topics=10, num_words=10, formatted=False)

# --- Function to generate labels with ChatGPT ---
def interpret_with_gpt(topic_id, keywords):
    prompt = f"""
    I have an LDA topic with these keywords: {', '.join(keywords)}.
    Please:
    1. Suggest a short label (3–6 words) summarizing the theme.
    2. Write one sentence describing the topic in plain English.
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",  # lightweight, cheap, good for summaries
        messages=[{"role": "user", "content": prompt}],
        temperature=0.5
    )
    return response.choices[0].message.content.strip()

# --- Run through all topics and get interpretations ---
topic_interpretations = {}
for topic_id, words in topics:
    keywords = [w for w, p in words]
    interpretation = interpret_with_gpt(topic_id, keywords)
    topic_interpretations[topic_id] = {
        "keywords": keywords,
        "interpretation": interpretation
    }

# --- Display results ---
for tid, result in topic_interpretations.items():
    print(f"\nTopic {tid}")
    print("Keywords:", ", ".join(result["keywords"]))
    print("Interpretation:\n", result["interpretation"])